### ISSUE TITLE
Possible to remove `bpick` 

### ISSUE THREAD

**Issue by vladdoster** [chalkygames123/dotfiles#1]
Hey, core maintainer of Zinit 👋🏻 

https://github.com/chalkygames123/dotfiles/blob/d3131033d435c4335da7a2a616d5f1ead3daca17/zshrc#L137

With recent updates, you can remove bpicks and it will select the correct binary for your system. I just thought I'd spread the news. 

<img width="2056" alt="Screen Shot 2022-05-13 at 04 37 15" src="https://user-images.githubusercontent.com/10052309/168256335-4428b570-f14e-44c7-9df5-54595171c65f.png">

Thanks for using Zinit!

**Comment by vladdoster** [comment]
<img width="2056" alt="Screen Shot 2022-05-13 at 04 40 21" src="https://user-images.githubusercontent.com/10052309/168256865-e2810f34-e5ba-4ed2-b633-4d3506d8b56a.png">

**Comment by chalkygames123** [comment]
Hi, thanks for letting me know. That's neat! However, it doesn't work with `volta-cli/volta`. Simply removing `bpick` will result in installing the arm64 binary on Intel Macs.

**Comment by vladdoster** [comment]
Yes, I have wrestled with this issue FOREVER haha. I actually opened a PR to fix their naming schema and they know it isn't great.

https://github.com/volta-cli/volta/pull/1194

It is due to the following error

They append `-aarch` to denote the ARM version, but leave the `x86` version without indicating it, see [here](https://github.com/volta-cli/volta/releases/tag/v1.0.5). It forces the pattern matching really ugly and I don't want that. I had this fixed and it landed in Zinit for a brief moment, but I removed it hoping no one would use Volta 😆 to make the patterns much cleaner. And removing it still allowed a previous [issue](https://github.com/zdharma-continuum/zinit/issues/179) to be fixed, but was the exact opposite of the issue you bring up. 

I opened an issue [zdharma-continuum/zinit/issues/270] to track this and I'll fix it this weekend. Thanks for taking time and give feedback!

**Comment by chalkygames123** [comment]
Got it. I'll keep an eye on that issue and close this issue once I can confirm that the problem has been resolved. Thanks for all your efforts.

**Comment by vladdoster** [comment]
@chalkygames123 The fix for this has been merged!

```
ᐳ what-system
OSTYPE=darwin17.7.0 MACHTYPE=x86_64 CPUTYPE=x86_64 hardware=x86_64 processor=i386

~
ᐳ zi from'gh-r' lbin'!' nocompile for @volta-cli/volta

Downloading volta-cli/volta…
(Requesting `volta-1.0.7-macos.tar.gz'…)
############################################################################################################################################ 100.0%
ziextract: Unpacking the files from: `volta-1.0.7-macos.tar.gz'…
ziextract: Successfully extracted and marked executable the appropriate files (volta, volta-migrate, volta-shim) contained in `volta-1.0.7-macos.tar.gz'.
linkbin annex: Created the volta soft link and set +x on the volta binary

~
ᐳ
```

**Comment by chalkygames123** [comment]
Hey, I've just confirmed that your fix does the trick! Thanks again.
